/**
 * Verifies edge-catalog manifest/files and keeps README mapping in sync.
 * Run: npx tsx scripts/audit-edge-cases-catalog.ts
 * Check (CI): npx tsx scripts/audit-edge-cases-catalog.ts --check
 */
import { existsSync, readFileSync, readdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

type ManifestEntry = {
	adapterKey: string;
	transport?: "sse" | "jsonl";
	adapterOptions?: Record<string, unknown>;
};

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const edgeDir = join(root, "test/fixtures/edge-catalog");
const manifestPath = join(edgeDir, "manifest.json");
const readmePath = join(edgeDir, "README.md");
const checkMode = process.argv.includes("--check");

function scenarioId(name: string): string {
	const match = name.match(/^(ec\d{2}|tier2-large-\d+)/u);
	return match?.[1]?.toUpperCase() ?? name.toUpperCase();
}

function scenarioSummary(name: string): string {
	const base = name.replace(/\.(sse|jsonl)$/u, "");
	const stem = base.replace(/^(ec\d{2}|tier2-large-\d+)-?/u, "");
	if (!stem) return "Tier-2 large stream stress fixture";
	return stem.replace(/-/g, " ");
}

function buildReadme(streamFiles: string[], manifest: Record<string, ManifestEntry>): string {
	const rows = streamFiles.map((file) => {
		const manifestKey = `edge-catalog/${file}`;
		const meta = manifest[manifestKey];
		const expected = file.replace(/\.(sse|jsonl)$/u, ".expected.json");
		const transport = meta.transport ?? (file.endsWith(".jsonl") ? "jsonl" : "sse");
		const hasOptions = meta.adapterOptions && Object.keys(meta.adapterOptions).length > 0;
		return {
			scenario: scenarioId(file),
			stream: file,
			expected,
			adapter: meta.adapterKey,
			transport,
			notes: hasOptions ? "custom adapterOptions" : "default adapter options",
		};
	});

	const lines: string[] = [
		"# Edge catalog mapping",
		"",
		"Generated by `scripts/audit-edge-cases-catalog.ts`.",
		"Each stream fixture in `edge-catalog/` maps to a manifest adapter key and expected golden output.",
		"",
		"## Scenario map",
		"",
		"| Scenario | Stream fixture | Expected fixture | Adapter key | Transport | Notes |",
		"| --- | --- | --- | --- | --- | --- |",
	];
	for (const row of rows) {
		lines.push(
			`| ${row.scenario} | \`${row.stream}\` | \`${row.expected}\` | \`${row.adapter}\` | ${row.transport} | ${row.notes} |`,
		);
	}
	lines.push("", "## Scenario summaries", "");
	for (const row of rows) {
		lines.push(`- **${row.scenario}**: ${scenarioSummary(row.stream)}.`);
	}
	lines.push("");
	return `${lines.join("\n")}\n`;
}

function main(): void {
	if (!existsSync(manifestPath)) {
		throw new Error("edge-catalog manifest.json is missing");
	}
	const manifest = JSON.parse(readFileSync(manifestPath, "utf8")) as Record<string, ManifestEntry>;
	const streamFiles = readdirSync(edgeDir)
		.filter((name) => name.endsWith(".sse") || name.endsWith(".jsonl"))
		.sort();

	if (streamFiles.length === 0) {
		throw new Error("edge-catalog has no stream fixtures");
	}

	for (const file of streamFiles) {
		const manifestKey = `edge-catalog/${file}`;
		const expectedPath = join(edgeDir, file.replace(/\.(sse|jsonl)$/u, ".expected.json"));
		const meta = manifest[manifestKey];
		if (!meta) throw new Error(`manifest missing entry for ${manifestKey}`);
		if (!meta.adapterKey) throw new Error(`manifest adapterKey missing for ${manifestKey}`);
		if (!existsSync(expectedPath)) throw new Error(`expected fixture missing for ${file}`);
		if (meta.transport && meta.transport !== (file.endsWith(".jsonl") ? "jsonl" : "sse")) {
			throw new Error(`manifest transport mismatch for ${manifestKey}`);
		}
	}

	for (const key of Object.keys(manifest)) {
		const file = key.replace(/^edge-catalog\//u, "");
		if (!streamFiles.includes(file)) {
			throw new Error(`manifest contains orphan entry ${key}`);
		}
	}

	const expectedReadme = buildReadme(streamFiles, manifest);
	if (checkMode) {
		if (!existsSync(readmePath)) {
			throw new Error("edge-catalog README.md is missing");
		}
		const current = readFileSync(readmePath, "utf8");
		if (current !== expectedReadme) {
			throw new Error("edge-catalog README drift: run npx tsx scripts/audit-edge-cases-catalog.ts");
		}
		console.log(`edge-catalog OK (${streamFiles.length} stream fixtures)`);
		return;
	}

	writeFileSync(readmePath, expectedReadme, "utf8");
	console.log(`wrote ${readmePath}`);
}

main();
